import type { Metadata } from "next";
import { Inter, Karantina } from "next/font/google";

import { Header } from "@/components";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700"],
});

const karantina = Karantina({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Carp Travel",
  description: "Generated by Next.js",
  openGraph: {
    title: "Carp Travel",
    description: "Carpathian’s Secrets",
    url: "https://carp-travel-beige.vercel.app",
    siteName: "CarpTravel",
    type: "website",
    images: [{ url: "/ogp/carptravel.webp" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header stylesFonts={karantina.className} />
        {children}
      </body>
    </html>
  );
}
